### ISSUE TITLE
Add Swiss and ISO27001 attributes to zone list

### ISSUE THREAD

**Issue by corvus-ch** [appuio/control-api#35]
### Summary

**As** a user
**I want** to see which zones are located in Switzerland and which are iso27001 complaint
**So that** I can choose the correct one should this be relevant to me.

### Context

The [marketing homepage](https://appuio.cloud) states that some zones have the attribute _Swiss_ and _ISO27001_. So far, it is not accessible to the users, which zones have those attributes and which do not.

### Further links

* https://kb.vshn.ch/appuio-cloud/references/architecture/control-api-zone.html
* https://github.com/appuio/appuio-io-docs

### Acceptance Criteria

* The Zone CRD has an additional attribute to express an arbitrary list of attributes/tags/labels.

### Implementation Ideas

1. _Swiss_ and _ISO27001_ are the attributes we currently know of. It is likely, that there will be more. So add another field that is an array of strings.
2. Make that a dictionary where the key is the attribute/tag/label name and the value is a URL documenting that thing.
3. Make the value a description field
4. Support both URL and description

**Comment by ccremer** [comment]
Why not add this information as a feature in the existing map? https://github.com/appuio/control-api/blob/aeba0a1ec5a5eed27989aa77a5c5ea8f10f5aa61/apis/v1/zone_types.go#L28

**Comment by corvus-ch** [comment]
> Why not add this information as a feature in the existing map?

You know, that thing with the tomatoes and the eyes 😛 

Thanks for pointing it out. How could I have missed that one? Still, I do not yet close this one. We might conclude that they are not the same.

**Comment by ccremer** [comment]
> We might conclude that they are not the same.

I agree. But for the time being we have the facility already, so might use it until we reach this conclusion.

**Comment by corvus-ch** [comment]
After some consideration, we figured that there is no need for this yet. Plus, we could model this with the existing features. Thus, I am closing this.
